version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha
      MONGO_INITDB_DATABASE: admin
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha
      ME_CONFIG_MONGODB_URL: mongodb://root:senha@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
      ME_CONFIG_BASICAUTH_USERNAME:  root
      ME_CONFIG_BASICAUTH_PASSWORD:  senha
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongo

  grupo-3-service:
    build: ./web/grupo-3
    container_name: grupo-3-container
    ports:
      - "8003:8083"
    volumes:
      - ./web/grupo-3:/app

  grupo-3-api:
    build: ./api/grupo-3
    container_name: grupo-3-api-container
    ports:
      - "3003:3003"
    volumes:
      - ./api/grupo-3:/app
    environment:
      - MONGODB_URL=${MONGODB_URL:-mongodb://root:senha@mongo:27017/}